apiVersion: v1
kind: PersistentVolume
metadata:
  name: litecoin-pv
  namespace: litecoin
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

